FROM registry.redhat.io/ubi9/go-toolset:9.7-1778675823@sha256:90a36bc2013b3fcb28e2a4b082c9b895d7c2c679e58b95aed9721970f3339d0e AS build
ENV APP_ROOT=/opt/app-root \
    GOPATH=/opt/app-root \
    CGO_ENABLED=1 \
    GOFLAGS="-buildvcs=false" \
    GOEXPERIMENT=strictfipsruntime

WORKDIR $APP_ROOT/src
ADD go.mod go.sum ./
ADD ./ ./

RUN go mod download && \
    git config --global --add safe.directory /opt/app-root/src && \
    go build -mod=mod -o updatetree -trimpath ./cmd/updatetree && \
    gzip -k updatetree && \
    make -f Build-clis.mak updatetree-cross-platform && \
    gzip updatetree-darwin-amd64 && \
    gzip updatetree-darwin-arm64 && \
    gzip updatetree-windows-amd64.exe

# Multi-Stage production build
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:12db9874bd753eb98b1ab3d840e75de5d6842ac0604fbd68c012adefe97140be AS deploy

# Add license file
COPY LICENSE /licenses/LICENSE

LABEL description="Trillian is an implementation of the concepts described in the Verifiable Data Structures white paper, which in turn is an extension and generalisation of the ideas which underpin Certificate Transparency."
LABEL io.k8s.description="Trillian is an implementation of the concepts described in the Verifiable Data Structures white paper."
LABEL io.k8s.display-name="updatetree"
LABEL io.openshift.tags="trillian updatetree trusted-artifact-signer"
LABEL summary="Provides the trillian updatetree binary for updating merkel trees."
LABEL com.redhat.component="updatetree"
LABEL name="rhtas/updatetree-rhel9"

COPY --from=build /opt/app-root/src/updatetree /
COPY --from=build /opt/app-root/src/updatetree.gz /usr/local/bin/updatetree.gz
COPY --from=build /opt/app-root/src/updatetree-darwin-amd64.gz /usr/local/bin/updatetree-darwin-amd64.gz
COPY --from=build /opt/app-root/src/updatetree-windows-amd64.exe.gz /usr/local/bin/updatetree-windows-amd64.exe.gz
COPY --from=build /opt/app-root/src/updatetree-darwin-arm64.gz /usr/local/bin/updatetree-darwin-arm64.gz

RUN chown root:0 updatetree && chmod g+wx updatetree && \
    chown root:0 /usr/local/bin/updatetree.gz && chmod g+wx /usr/local/bin/updatetree.gz && \
    chown root:0 /usr/local/bin/updatetree-darwin-amd64.gz && chmod g+wx /usr/local/bin/updatetree-darwin-amd64.gz && \
    chown root:0 /usr/local/bin/updatetree-darwin-arm64.gz && chmod g+wx /usr/local/bin/updatetree-darwin-arm64.gz && \
    chown root:0 /usr/local/bin/updatetree-windows-amd64.exe.gz && chmod g+wx /usr/local/bin/updatetree-windows-amd64.exe.gz

##Configure home directory
ENV HOME=/home
RUN chgrp -R 0 /${HOME} && chmod -R g=u /${HOME}

WORKDIR ${HOME}

# Do not run as root
USER 1001

# Set the binary as the entrypoint of the container
ENTRYPOINT ["/updatetree"]
