FROM registry.redhat.io/ubi9/go-toolset:9.8-1788409979@sha256:5e68f09a652ac6627a83c57655e42e24575efb278b54336039c9308607fc6b21 AS builder
ENV APP_ROOT=/opt/app-root
ENV GOPATH=$APP_ROOT
ENV CGO_ENABLED=0
ENV GOFIPS140=v1.0.0

USER root
WORKDIR $APP_ROOT/src/
ADD go.mod go.sum $APP_ROOT/src/
RUN go mod download
RUN git config --global --add safe.directory /opt/app-root/src

# Add source code
ADD ./ $APP_ROOT/src/

RUN go mod edit -godebug=fips140=auto && \
    go build -mod=mod -tags 'postgresql,mysql,k8s,no_openssl' -v ./cmd/trillian_log_signer

# Multi-Stage production build
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:7fbeae18dc9476399f565e68255f602a3374ea8614ba3d14843565131a13ff93 AS deploy

# Retrieve the binary from the previous stage
COPY --from=builder /opt/app-root/src/trillian_log_signer /
COPY LICENSE /licenses/license.txt

LABEL description="Trillian is an implementation of the concepts described in the Verifiable Data Structures white paper, which in turn is an extension and generalisation of the ideas which underpin Certificate Transparency."
LABEL io.k8s.description="Trillian is an implementation of the concepts described in the Verifiable Data Structures white paper."
LABEL io.k8s.display-name="trillian_log_signer"
LABEL io.openshift.tags="trillian-logsigner trusted-signer"
LABEL summary="Provides the trillian logsigner binary for running trillian logsigner"
LABEL com.redhat.component="trillian_log_signer"
LABEL name="rhtas/trillian-logsigner-rhel9"

USER 65532:65532

# Set the binary as the entrypoint of the container
ENTRYPOINT ["/trillian_log_signer"]
