FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:f598528219a1be07cf520fbe82a2d2434dc9841e1f0a878382c8a13bf42cb486

LABEL description="Netcat is a computer networking utility for reading from and writing to network connections using TCP or UDP."
LABEL io.k8s.description="netcat is a computer networking utility for reading from and writing to network connections using TCP or UDP."
LABEL io.k8s.display-name="trillian_netcat"
LABEL io.openshift.tags="trillian netcat trusted-signer"
LABEL summary="Provides the trillian netcat binary for running trillian netcat"

RUN microdnf -y install nc
