FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:2a98ec380ad75004992b8538380a5003da64442f0a69237ed236859e023c71d0

LABEL description="Netcat is a computer networking utility for reading from and writing to network connections using TCP or UDP."
LABEL io.k8s.description="netcat is a computer networking utility for reading from and writing to network connections using TCP or UDP."
LABEL io.k8s.display-name="trillian_netcat"
LABEL io.openshift.tags="trillian netcat trusted-signer"
LABEL summary="Provides the trillian netcat binary for running trillian netcat"

RUN microdnf -y install nc
