FROM registry.access.redhat.com/ubi9/go-toolset@sha256:cbc354aed85c826d3b6d6d16250a46b1af0bf5805d109b200bc1998119c8ed29 AS builder
ENV APP_ROOT=/opt/app-root
ENV GOPATH=$APP_ROOT
ENV CGO_ENABLED=false
ENV -buildvcs=false

WORKDIR $APP_ROOT/src/
ADD go.mod go.sum $APP_ROOT/src/
RUN go mod download
RUN git config --global --add safe.directory /opt/app-root/src

# Add source code
ADD ./ $APP_ROOT/src/

RUN go build -v ./cmd/trillian_log_signer

# Multi-Stage production build
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:8b314e254e9ab9a7a08b675fcfd3ed66a2943eeda7b26395210d451569976b9b AS deploy

# Retrieve the binary from the previous stage
COPY --from=builder /opt/app-root/src/trillian_log_signer /

LABEL description="Trillian is an implementation of the concepts described in the Verifiable Data Structures white paper, which in turn is an extension and generalisation of the ideas which underpin Certificate Transparency."
LABEL io.k8s.description="Trillian is an implementation of the concepts described in the Verifiable Data Structures white paper."
LABEL io.k8s.display-name="trillian_log_signer"
LABEL io.openshift.tags="trillian-logsigner trusted-signer"
LABEL summary="Provides the trillian logsigner binary for running trillian logsigner"
LABEL com.redhat.component="trillian_log_signer"
LABEL name="trillian_log_signer"

# Set the binary as the entrypoint of the container
ENTRYPOINT ["/trillian_log_signer"]
