FROM registry.redhat.io/ubi9/go-toolset:9.8-1790174511@sha256:0a4666f7a4eb0644c97a73cba198eb268691b270d97831822689e7a2088f87be AS build
ENV APP_ROOT=/opt/app-root \
    GOPATH=/opt/app-root \
    CGO_ENABLED=1 \
    GOFLAGS="-buildvcs=false" \
    GOEXPERIMENT=strictfipsruntime

WORKDIR $APP_ROOT/src
ADD go.mod go.sum ./
ADD ./ ./

RUN go mod download && \
    git config --global --add safe.directory /opt/app-root/src && \
    go build -mod=mod -o createtree -trimpath ./cmd/createtree

# Multi-Stage production build
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:8ebe2ad8fdf3cab3e5a53c1edc69194c98209cfadab24b884f4ad9ebcf7bbbfc AS deploy

# Add license file
COPY LICENSE /licenses/LICENSE

LABEL description="Trillian is an implementation of the concepts described in the Verifiable Data Structures white paper, which in turn is an extension and generalisation of the ideas which underpin Certificate Transparency."
LABEL io.k8s.description="Trillian is an implementation of the concepts described in the Verifiable Data Structures white paper."
LABEL io.k8s.display-name="createtree"
LABEL io.openshift.tags="trillian createtree trusted-artifact-signer"
LABEL summary="Provides the trillian createtree binary for creating merkel trees."
LABEL com.redhat.component="createtree"
LABEL name="rhtas/createtree-rhel9"

COPY --from=build /opt/app-root/src/createtree /createtree

RUN chown root:0 createtree && chmod g+wx createtree

# Configure home directory
ENV HOME=/home
RUN chgrp -R 0 /${HOME} && chmod -R g=u /${HOME}

WORKDIR ${HOME}

# Do not run as root
USER 1001

# Set the binary as the entrypoint of the container
ENTRYPOINT ["/createtree"]
