FROM registry.redhat.io/rhel9/redis-6@sha256:3f9e2b4637085be73cdcd2d9425dab937825380753e57271ef5c58519e9e6483

LABEL description="Securesign redis is built ontop of rhel9/redis-6 but accepts external connections and runs appendonly mode with full durability."
LABEL io.k8s.description="Securesign redis is built ontop of rhel9/redis-6 but accepts external connections and runs appendonly mode with full durability."
LABEL io.k8s.display-name="redis container image for Red Hat trusted artifact signer."
LABEL io.openshift.tags="redis, Red Hat trusted artifact signer."
LABEL summary="Runs redis in appendonly mode with enablement for external connections by default."
LABEL com.redhat.component="redis"
LABEL name="rhtas/trillian-redis-rhel9"
COPY LICENSE /licenses/license.txt
USER 1001

RUN sed -i 's/#bind 127.0.0.1 -::1/bind 0.0.0.0/g' /etc/redis/redis.conf && sed -i 's/appendonly no/appendonly yes/g' /etc/redis/redis.conf

ENTRYPOINT ["container-entrypoint"]
CMD ["run-redis"]
