apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/build-nudge-files: controllers/constants/*
    build.appstudio.openshift.io/repo: https://github.com/securesign/trillian?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main" && ( "60-load-db.sh".pathChanged() || "examples/deployment/docker/db_server/mysql.cnf".pathChanged()
      || "storage/mysql/schema/storage.sql".pathChanged() || ".tekton/database-push.yaml".pathChanged()
      || "Dockerfile.database.rh".pathChanged() || "trigger-konflux-builds.txt".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: tas-components
    appstudio.openshift.io/component: database
    pipelines.appstudio.openshift.io/type: build
  name: database-on-push
  namespace: rhtas-tenant
spec:
  params:
  - name: dockerfile
    value: Dockerfile.database.rh
  - name: git-url
    value: '{{repo_url}}'
  - name: output-image
    value: quay.io/securesign/trillian-database:{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: build-source-image
    value: "true"
  - name: prefetch-input
    value: '{"type": "gomod", "path": "."}'
  - name: hermetic
    value: "true"
  - name: go_unit_test
    value: "true"
  - name: go_test_command
    value: go test $(go list ./... | grep -v /storage/ | grep -v /client/ | grep -v
      /quota/crdbqm )
  - name: fips-check
    value: "true"
  pipelineRef:
    params:
    - name: url
      value: https://github.com/securesign/pipelines.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/docker-build-oci-ta.yaml
    resolver: git
  taskRunSpecs:
  - pipelineTaskName: run-unit-test
    stepSpecs:
    - computeResources:
        limits:
          cpu: "3"
          memory: 3Gi
        requests:
          cpu: "3"
          memory: 3Gi
      name: run-tests
  taskRunTemplate:
    serviceAccountName: build-pipeline-database
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
