apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/build-nudge-files: controllers/constants/*
    build.appstudio.openshift.io/repo: https://github.com/securesign/trillian?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "release-1.2" && ( ".tekton/redis-push.yaml".pathChanged() || "Dockerfile.redis.rh".pathChanged()
      || "trigger-konflux-builds.txt".pathChanged()  )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: tas-components-v1-2
    appstudio.openshift.io/component: redis-v1-2
    pipelines.appstudio.openshift.io/type: build
  name: redis-v1-2-on-push
  namespace: rhtas-tenant
spec:
  params:
  - name: release-version
    value: "1.2.2"
  - name: dockerfile
    value: Dockerfile.redis.rh
  - name: git-url
    value: '{{source_url}}'
  - name: output-image
    value: quay.io/securesign/trillian-redis:{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: build-source-image
    value: "true"
  - name: prefetch-input
    value: ""
  - name: hermetic
    value: "true"
  pipelineRef:
    params:
    - name: url
      value: https://github.com/securesign/pipelines.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/docker-build-oci-ta.yaml
    resolver: git
  taskRunTemplate:
    serviceAccountName: build-pipeline-redis-v1-2
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
