apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: go-unit-test
  annotations:
    tekton.dev/title: "Go Unit Test Task"
spec:
  workspaces:
    - name: source
  steps:
    - name: run-tests
      image: registry.access.redhat.com/ubi9/go-toolset@sha256:75b74b4d4f589965d1d1d2086b951f543cf0c8152693a8640ea09a0c3b14f9e3
      workingDir: $(workspaces.source.path)/source
      script: |
        #!/usr/bin/env sh
        go mod vendor
        go test $(go list ./... | grep -v /storage/ | grep -v /client/ )

# This file bundles the unit tests for trillian. 
# If any changes are made to this file, it must be pushed to Quay using the following command:
# 'tkn bundle push quay.io/securesign/trillian-unit-test:latest -f .tekton/trillian-unit-test.yaml'.