apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/securesign/trillian?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" &&
      ( ".tekton/updatetree-push.yaml".pathChanged() || "Dockerfile.updatetree.rh".pathChanged() || "trigger-konflux-builds.txt".pathChanged() || "go.mod".pathChanged() || "go.sum".pathChanged() || "cmd/updatetree".pathChanged() || "client".pathChanged() || "Build-clis.mak".pathChanged() )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: trillian
    appstudio.openshift.io/component: updatetree
    pipelines.appstudio.openshift.io/type: build
  name: updatetree-on-push
  namespace: rhtas-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/securesign/trillian-updatetree:{{revision}}
  - name: dockerfile
    value: Dockerfile.updatetree.rh
  - name: build-source-image
    value: true
  - name: prefetch-input
    value: '{"type": "gomod", "path": "."}'
  - name: hermetic
    value: true
  - name: go_unit_test
    value: true
  - name: go_test_command
    value: go test $(go list ./... | grep -v /storage/ | grep -v /client/ | grep -v /quota/crdbqm )
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: 'https://github.com/securesign/pipelines.git'
      - name: revision
        value: 'main'
      - name: pathInRepo
        value: 'pipelines/docker-build-oci-ta.yaml'
  taskRunTemplate: {}
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
